name: Deploy

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  check-latest: true
                  registry-url: https://registry.npmjs.org/
            - uses: pnpm/action-setup@v2
              with:
                  version: 8.6.2
                  run_install: |
                      - recursive: true
                        args: [--frozen-lockfile, --strict-peer-dependencies]
            - name: Build
              run: npm run build
            - name: Deploy with gh-pages
              run: |
                  git config --global user.name github-actions
                  git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
                  git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
                  npx gh-pages -d dist
